spring:
  session:
    timeout: 86400
    store-type: redis

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    database: 1
    port: 6379
    host: 122.51.116.77
    password: 123456

  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/userUniverse
    username: root
    password: 12345678
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.aiyichen.admindemo.controller

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  reactive:
    session:
      timeout: 86400


  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost

